name: Setup new devices on inventory
run-name: ${{ github.actor }} is deploying new devices on inventory (#${{ github.run_number }})

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/inventory/**'
  workflow_dispatch:

jobs:
  approve-setup:
    runs-on: "self-hosted"
    steps:
      - name: Approval
        env:
          DEPLOY_APPROVERS: ${{ vars.DEPLOY_APPROVERS }}
        uses: fjogeleit/workflow-approval-action@v2
        with:
          approvers: '${{ env.DEPLOY_APPROVERS }}'

  setup:
    needs: "approve-setup"
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure mkadmin user exists
        env:
          MKADMIN_USERNAME: ${{ vars.MKADMIN_USERNAME }}
          MKADMIN_PASSWORD: ${{ secrets.MKADMIN_PASSWORD }}
        run: |
          if id "${MKADMIN_USERNAME}" &>/dev/null; then
              echo "User '${MKADMIN_USERNAME}' already exists."
          else
              sudo useradd -m -s /bin/bash "${MKADMIN_USERNAME}"
              echo "${MKADMIN_USERNAME}:${NEW_USER_PASSWORD}" | sudo chpasswd
              sudo usermod -aG sudo "${MKADMIN_PASSWORD}"
              echo "User '${MKADMIN_USERNAME}' created."
          fi
