name: Setup new devices on inventory
run-name: ${{ github.actor }} is deploying new devices on inventory (#${{ github.run_number }})

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  approve-setup:
    runs-on: "self-hosted"
    steps:
      - name: Approval
        id: approval
        run: |
          echo "Waiting for manual approval..."
          read -p "Press enter to continue"

  setup:
    needs: "approve-setup"
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: echo "Debugging step to check if workflow is triggered"

      - name: Ensure mkadmin user exists
        env:
          MKADMIN_USERNAME: ${{ vars.MKADMIN_USERNAME }}
          MKADMIN_PASSWORD: ${{ secrets.MKADMIN_PASSWORD }}
        run: |
          if id "${MKADMIN_USERNAME}" &>/dev/null; then
              echo "User '${MKADMIN_USERNAME}' already exists."
          else
              sudo useradd -m -s /bin/bash "${MKADMIN_USERNAME}"
              echo "${MKADMIN_USERNAME}:${MKADMIN_PASSWORD}" | sudo chpasswd
              sudo usermod -aG sudo "${MKADMIN_USERNAME}"
              echo "User '${MKADMIN_USERNAME}' created."
          fi
